pipeline fix

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -155,12 +155,14 @@ jobs:
           DEPLOY_PATH: /pso/stock-hub
         run: |
           rsync -avz --exclude '.git' --exclude 'key.tar.gz' ./ root@217.15.160.69:${{ env.DEPLOY_PATH }}
-          ssh root@217.15.160.69 "cd ${{ env.DEPLOY_PATH }} && composer install && php artisan migrate --force"
+          ssh root@217.15.160.69 "
+            cd ${{ env.DEPLOY_PATH }} &&
+            composer install &&
+            php artisan migrate --force || echo 'Migration failed!'
+          "
 
       # Reload Web Server
       - name: Reload Web Server
         run: |
-          ssh root@217.15.160.69 "systemctl reload nginx"
-
           ssh root@217.15.160.69 "systemctl reload nginx"
 
